### ISSUE TITLE
[Bug Report] colors in signs disappear

### ISSUE THREAD

**Issue by mote166** [JaxkDev/koth#16]
**Describe the bug in detail**
when i install this plugin and try to put colors in a sign they disappear.

**To Reproduce**
Steps to reproduce the behaviour:
1. install the latest unpacked version from master.
2. place a sign and try to put a colored word and taadda, no colors.

(no errors.)

**Expected behaviour**
any word to be colored in signs

**Actual behaviour**
no colors 

**Screenshots**
Add screenshots to help explain your problem.

**Host (please complete the following information):**
 - OS: [e.g. Windows10]
 - PocketMine Version:  3.10.1 (unofficial) AND NOT THE CAUSE
 - Plugin Version: sorry idk but its the latest src right now

**Player Device (If applicable | please complete the following information):**
 - Device: all
 - OS: all
 - MCPE Version: 1.13.0

**Server Log (IMPORTANT)**
Please have both pmmp's debug option set to '2' and koth's debug option enabled.
Please paste your server.log content using https://pastebin.com

**Additional context/notes**
Add any other context/notes about the problem here.

**Comment by JaxkDev** [comment]
Nothing to prove that this plugin is causing that, plus unofficial PMMP no matter the cause no support.
