### ISSUE TITLE
[Suggestion] Better timer display

### ISSUE THREAD

**Issue by TheUtopianPlayz** [JaxkDev/koth#19]
im not a big fan of u actually having to run /koth leave for it to detect that ur not in the koth, my players could /spawn or something to leave still be counted in the koth

also the koth timer for auto start should be in mins not secs, if i wanted to set up a koth to start every hour and broadcast a message every 10 mins the timer broadcast would say "starting in 3600, 3300, ect

**Comment by JaxkDev** [comment]
For the first part, that’s one of the reasons behind the ability to disable commands when in the game.

For the timings, it will stay in seconds but the display could be cleaner.

**Comment by TheUtopianPlayz** [comment]
Yes but I feel players should still be able to /spawn if needed

**Comment by JaxkDev** [comment]
`/koth leave` teleport's them to where they were before joining, I'm not going to hard-code a specific white-list

**Comment by JaxkDev** [comment]
So I guess this was why secToHR was added...
