### ISSUE TITLE
[Bug Report] Config.yml won't save

### ISSUE THREAD

**Issue by Ignaciox** [JaxkDev/koth#25]
**Describe the bug in detail**
Whenever you edit the config.yml file provided with the plugin, it will revert itself after you restart the server. Whether it might be setting something from true to false, it will revert itself.

**To Reproduce**
Steps to reproduce the behaviour:
1: Go to path /PocketMine-MP/plugin_data/KOTH
2: Config.yml is the file that keeps reverting after a server restart.
3: set something to true or false depending on what's it's currently set as.
4: save and restart the server. and ta-da all your changes are gone.

**Expected behaviour**
For my changes to config.yml to be not reverted and actually saved

**Actual behaviour**
Config.yml keeps reverting itself.

**Screenshots**
Add screenshots to help explain your problem.

**Host (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS
 - PocketMine Version:  3.12.5
 - Plugin Version: KOTH_v1.0.0-Beta4

**Player Device (If applicable | please complete the following information):**
Not applicable.

**Server Log (IMPORTANT)**
Unable to set debug on because of config.yml not saving+ the console tells me nothing the plugin just disables itself after a restart and re-enables itself with no errors displaying.

**Additional context/notes**
If you need any additional information or something from the console that you find useful since i was unable to find anything of significant use let me know.

**Comment by JaxkDev** [comment]
Finally a half decent report, but it’s missing the log

**Comment by JaxkDev** [comment]
>the plugin just disables itself after a restart and re-enables itself
The plugin doesn’t do that...

**Comment by Ignaciox** [comment]
Saving config file and rebooting server
[18:15:29] [Server thread/INFO]: Disabling KOTH v1.0.0-Beta4

[18:15:35] [Server thread/INFO]: Loading KOTH v1.0.0-Beta4

[18:15:36] [Server thread/INFO]: Enabling KOTH v1.0.0-Beta4

no other errors. I know it's not much to go on but could you look into it as i literally have nothing else to give you because it's not telling me anything else. Plugin itself works it doesn't lose the data it's just the config i'm unable to make edits to.

**Comment by JaxkDev** [comment]
To go around this edit config in this order:
- **Stop server**
- Edit config
- Start server

(DO NOT UPDATE CONFIG WHILE SERVER IS RUNNING)

Update will be soon, probably just be lazy and do beta4.1
